apiVersion: apps/v1
kind: Deployment
metadata:
  name: cupidcome-deployment
spec:
  selector:
    matchLabels:
      app: cupidcome
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cupidcome
    spec:
      containers:
      - name: cupidcome
        image: bidianqing/cupidcome:1.0
        ports:
        - containerPort: 80